name: "Build Production image"
on:
  release:
    types: ['published']

jobs:
  build-image:
    name: 'Build & Push Production container image'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm/v6
          # - linux/arm/v7
          - linux/arm64
    outputs:
      webserver_meta_json: ${{ steps.meta.outputs.json }}
      webserver_meta_version: ${{ steps.meta.outputs.version }}
    steps:
      - name: 'Prepare Artifact Name'
        id: prepare-artifact-name
        shell: bash
        run: |
          platform=${{ matrix.platform }}
          echo "platform=${platform//\//-}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.DOCKERHUB_IMAGE }}
          tags: |
            type=ref,event=tag
            type=sha,prefix=,format=short
            type=sha,prefix=,format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        id: build
        with:
          target: runtime
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=${{ vars.DOCKERHUB_IMAGE }},push-by-digest=true,name-canonical=true,push=true

      - name: 'Export image digest'
        run: |
          mkdir -p /tmp/digests/runtime
          rm -rf /tmp/digests/runtime/*
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/runtime/${digest#sha256:}"

      - name: 'Upload digest'
        uses: actions/upload-artifact@v4
        with:
          name: digests-runtime-${{ steps.prepare-artifact-name.outputs.platform }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1


  merge-images:
    name: 'Merge digests and push manifests'
    runs-on: ubuntu-22.04
    needs:
      - build-image
    steps:
      - name: 'Download digests'
        uses: actions/download-artifact@v4
        with:
          pattern: digests-runtime-*
          path: /tmp/digests
          merge-multiple: true

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Create webserver manifest list and push'
        working-directory: /tmp/digests/runtime
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{ needs.build-image.outputs.webserver_meta_json }}
        run: |
          tags=$(jq -cer '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") || { echo "Failed processing image metadata"; exit 1; }
          docker buildx imagetools create $tags \
            $(printf '${{ vars.DOCKERHUB_IMAGE }}@sha256:%s ' *)

      - name: 'Inspect image'
        run: |
          docker buildx imagetools inspect ${{ vars.DOCKERHUB_IMAGE }}:${{ needs.build-image.outputs.webserver_meta_version }}
