name: "Build Production image"
on:
  release:
    types: ['published']

jobs:
  build-image:
    name: 'Build & Push Production container image'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.DOCKERHUB_IMAGE }}
          tags: |
            type=ref,event=tag
            type=sha,prefix=,format=short
            type=sha,prefix=,format=long
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: runtime
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max